# Version 2023-11-29
from collections import namedtuple

system = namedtuple("system", ["id", "no_ammonia", "id_cluster", "path", "ener", "path_pdb", "pdb", "traj"])
systems = {
	21: system(id=21, no_ammonia='02', id_cluster='1', path='ammonia-02-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-02-1.pdb', traj='small-clusters-pos-1.xyz'),
	22: system(id=22, no_ammonia='02', id_cluster='2', path='ammonia-02-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-02-2.pdb', traj='small-clusters-pos-1.xyz'),
	34: system(id=34, no_ammonia='03', id_cluster='4', path='ammonia-03-4/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-03-4.pdb', traj='small-clusters-pos-1.xyz'),
	41: system(id=41, no_ammonia='04', id_cluster='1', path='ammonia-04-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-04-1.pdb', traj='small-clusters-pos-1.xyz'),
	42: system(id=42, no_ammonia='04', id_cluster='2', path='ammonia-04-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-04-2.pdb', traj='small-clusters-pos-1.xyz'),
	44: system(id=44, no_ammonia='04', id_cluster='4', path='ammonia-04-4/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-04-4.pdb', traj='small-clusters-pos-1.xyz'),
	51: system(id=51, no_ammonia='05', id_cluster='1', path='ammonia-05-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-05-1.pdb', traj='small-clusters-pos-1.xyz'),
	54: system(id=54, no_ammonia='05', id_cluster='4', path='ammonia-05-4/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-05-4.pdb', traj='small-clusters-pos-1.xyz'),
	62: system(id=62, no_ammonia='06', id_cluster='2', path='ammonia-06-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-06-2.pdb', traj='small-clusters-pos-1.xyz'),
	71: system(id=71, no_ammonia='07', id_cluster='1', path='ammonia-07-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-07-1.pdb', traj='small-clusters-pos-1.xyz'),
	81: system(id=81, no_ammonia='08', id_cluster='1', path='ammonia-08-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-08-1.pdb', traj='small-clusters-pos-1.xyz'),
	82: system(id=82, no_ammonia='08', id_cluster='2', path='ammonia-08-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-08-2.pdb', traj='small-clusters-pos-1.xyz'),
	83: system(id=83, no_ammonia='08', id_cluster='3', path='ammonia-08-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-08-3.pdb', traj='small-clusters-pos-1.xyz'),
	101: system(id=101, no_ammonia='10', id_cluster='1', path='ammonia-10-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-10-1.pdb', traj='small-clusters-pos-1.xyz'),
	102: system(id=102, no_ammonia='10', id_cluster='2', path='ammonia-10-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-10-2.pdb', traj='small-clusters-pos-1.xyz'),
	103: system(id=103, no_ammonia='10', id_cluster='3', path='ammonia-10-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-10-3.pdb', traj='small-clusters-pos-1.xyz'),
	121: system(id=121, no_ammonia='12', id_cluster='1', path='ammonia-12-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-12-1.pdb', traj='small-clusters-pos-1.xyz'),
	122: system(id=122, no_ammonia='12', id_cluster='2', path='ammonia-12-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-12-2.pdb', traj='small-clusters-pos-1.xyz'),
	123: system(id=123, no_ammonia='12', id_cluster='3', path='ammonia-12-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-12-3.pdb', traj='small-clusters-pos-1.xyz'),
	141: system(id=141, no_ammonia='14', id_cluster='1', path='ammonia-14-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-14-1.pdb', traj='small-clusters-pos-1.xyz'),
	142: system(id=142, no_ammonia='14', id_cluster='2', path='ammonia-14-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-14-2.pdb', traj='small-clusters-pos-1.xyz'),
	143: system(id=143, no_ammonia='14', id_cluster='3', path='ammonia-14-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-14-3.pdb', traj='small-clusters-pos-1.xyz'),
	161: system(id=161, no_ammonia='16', id_cluster='1', path='ammonia-16-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-16-1.pdb', traj='small-clusters-pos-1.xyz'),
	162: system(id=162, no_ammonia='16', id_cluster='2', path='ammonia-16-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-16-2.pdb', traj='small-clusters-pos-1.xyz'),
	163: system(id=163, no_ammonia='16', id_cluster='3', path='ammonia-16-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-16-3.pdb', traj='small-clusters-pos-1.xyz'),
	201: system(id=201, no_ammonia='20', id_cluster='1', path='ammonia-20-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-20-1.pdb', traj='small-clusters-pos-1.xyz'),
	202: system(id=202, no_ammonia='20', id_cluster='2', path='ammonia-20-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-20-2.pdb', traj='small-clusters-pos-1.xyz'),
	203: system(id=203, no_ammonia='20', id_cluster='3', path='ammonia-20-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-20-3.pdb', traj='small-clusters-pos-1.xyz'),
	241: system(id=241, no_ammonia='24', id_cluster='1', path='ammonia-24-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-24-1.pdb', traj='small-clusters-pos-1.xyz'),
	242: system(id=242, no_ammonia='24', id_cluster='2', path='ammonia-24-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-24-2.pdb', traj='small-clusters-pos-1.xyz'),
	243: system(id=243, no_ammonia='24', id_cluster='3', path='ammonia-24-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-24-3.pdb', traj='small-clusters-pos-1.xyz'),
	281: system(id=281, no_ammonia='28', id_cluster='1', path='ammonia-28-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-28-1.pdb', traj='small-clusters-pos-1.xyz'),
	282: system(id=282, no_ammonia='28', id_cluster='2', path='ammonia-28-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-28-2.pdb', traj='small-clusters-pos-1.xyz'),
	283: system(id=283, no_ammonia='28', id_cluster='3', path='ammonia-28-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-28-3.pdb', traj='small-clusters-pos-1.xyz'),
	321: system(id=321, no_ammonia='32', id_cluster='1', path='ammonia-32-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-32-1.pdb', traj='small-clusters-pos-1.xyz'),
	322: system(id=322, no_ammonia='32', id_cluster='2', path='ammonia-32-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-32-2.pdb', traj='small-clusters-pos-1.xyz'),
	323: system(id=323, no_ammonia='32', id_cluster='3', path='ammonia-32-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-32-3.pdb', traj='small-clusters-pos-1.xyz'),
	361: system(id=361, no_ammonia='36', id_cluster='1', path='ammonia-36-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-36-1.pdb', traj='small-clusters-pos-1.xyz'),
	362: system(id=362, no_ammonia='36', id_cluster='2', path='ammonia-36-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-36-2.pdb', traj='small-clusters-pos-1.xyz'),
	363: system(id=363, no_ammonia='36', id_cluster='3', path='ammonia-36-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-36-3.pdb', traj='small-clusters-pos-1.xyz'),
	401: system(id=401, no_ammonia='40', id_cluster='1', path='ammonia-40-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-40-1.pdb', traj='small-clusters-pos-1.xyz'),
	402: system(id=402, no_ammonia='40', id_cluster='2', path='ammonia-40-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-40-2.pdb', traj='small-clusters-pos-1.xyz'),
	403: system(id=403, no_ammonia='40', id_cluster='3', path='ammonia-40-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-40-3.pdb', traj='small-clusters-pos-1.xyz'),
	481: system(id=481, no_ammonia='48', id_cluster='1', path='ammonia-48-1/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-48-1.pdb', traj='small-clusters-pos-1.xyz'),
	482: system(id=482, no_ammonia='48', id_cluster='2', path='ammonia-48-2/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-48-2.pdb', traj='small-clusters-pos-1.xyz'),
	483: system(id=483, no_ammonia='48', id_cluster='3', path='ammonia-48-3/production', ener='small-clusters-1.ener', path_pdb='pdb_coordinates', pdb='ammonia-48-3.pdb', traj='small-clusters-pos-1.xyz'),
}
